name: TheResearchLAB
favicon: null
layout_spectrum: 0.9329065114725381
typography_spectrum: 0.0006950672250241041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.807200345909223
  lightness: 0.7819876882713288
  saturation: 0.38985918718390167
  rhythmicContrast: 0.8886506618000567
purpose: []
